version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=crud_app
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    build: .
    container_name: crud-app
    environment:
      - DB_HOST=mariadb
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_NAME=crud_app
    ports:
      - "3000:3000"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
